
// Automatically generated configuration file.

# ifndef __MBED_CONFIG_DATA__
# define __MBED_CONFIG_DATA__

// Configuration parameters

#if !defined(MBED_CONF_PLATFORM_FORCE_NON_COPYABLE_ERROR)
	#define MBED_CONF_PLATFORM_FORCE_NON_COPYABLE_ERROR (0)
#endif
#if !defined(MBED_CONF_EVENTS_SHARED_HIGHPRIO_EVENTSIZE)
	#define MBED_CONF_EVENTS_SHARED_HIGHPRIO_EVENTSIZE (256)
#endif
#if !defined(MBED_CONF_PLATFORM_STDIO_BAUD_RATE)
	#define MBED_CONF_PLATFORM_STDIO_BAUD_RATE (9600)
#endif
#if !defined(MBED_CONF_EVENTS_SHARED_HIGHPRIO_STACKSIZE)
	#define MBED_CONF_EVENTS_SHARED_HIGHPRIO_STACKSIZE (1024)
#endif
#if !defined(MBED_LFS_ENABLE_INFO)
	#define MBED_LFS_ENABLE_INFO (0)
#endif
#if !defined(MBED_CONF_PPP_CELL_IFACE_APN_LOOKUP)
	#define MBED_CONF_PPP_CELL_IFACE_APN_LOOKUP (0)
#endif
#if !defined(MBED_CONF_EVENTS_SHARED_DISPATCH_FROM_APPLICATION)
	#define MBED_CONF_EVENTS_SHARED_DISPATCH_FROM_APPLICATION (0)
#endif
#if !defined(MBED_CONF_PLATFORM_STDIO_CONVERT_NEWLINES)
	#define MBED_CONF_PLATFORM_STDIO_CONVERT_NEWLINES (0)
#endif
#if !defined(MBED_CONF_PLATFORM_DEFAULT_SERIAL_BAUD_RATE)
	#define MBED_CONF_PLATFORM_DEFAULT_SERIAL_BAUD_RATE (9600)
#endif
#if !defined(MBED_LFS_LOOKAHEAD)
	#define MBED_LFS_LOOKAHEAD (512)
#endif
#if !defined(MBED_CONF_PLATFORM_STDIO_FLUSH_AT_EXIT)
	#define MBED_CONF_PLATFORM_STDIO_FLUSH_AT_EXIT (1)
#endif
#if !defined(MBED_CONF_PPP_CELL_IFACE_AT_PARSER_TIMEOUT)
	#define MBED_CONF_PPP_CELL_IFACE_AT_PARSER_TIMEOUT (8000)
#endif
#if !defined(MBED_LFS_PROG_SIZE)
	#define MBED_LFS_PROG_SIZE (64)
#endif
#if !defined(MBED_CONF_EVENTS_SHARED_EVENTSIZE)
	#define MBED_CONF_EVENTS_SHARED_EVENTSIZE (256)
#endif
#if !defined(MBED_CONF_PPP_CELL_IFACE_AT_PARSER_BUFFER_SIZE)
	#define MBED_CONF_PPP_CELL_IFACE_AT_PARSER_BUFFER_SIZE (256)
#endif
#if !defined(MBED_LFS_BLOCK_SIZE)
	#define MBED_LFS_BLOCK_SIZE (512)
#endif
#if !defined(MBED_CONF_PPP_CELL_IFACE_BAUD_RATE)
	#define MBED_CONF_PPP_CELL_IFACE_BAUD_RATE (115200)
#endif
#if !defined(MBED_CONF_EVENTS_USE_LOWPOWER_TIMER_TICKER)
	#define MBED_CONF_EVENTS_USE_LOWPOWER_TIMER_TICKER (0)
#endif
#if !defined(MBED_LFS_READ_SIZE)
	#define MBED_LFS_READ_SIZE (64)
#endif
#if !defined(MBED_CONF_DRIVERS_UART_SERIAL_TXBUF_SIZE)
	#define MBED_CONF_DRIVERS_UART_SERIAL_TXBUF_SIZE (256)
#endif
#if !defined(MBED_CONF_DRIVERS_UART_SERIAL_RXBUF_SIZE)
	#define MBED_CONF_DRIVERS_UART_SERIAL_RXBUF_SIZE (256)
#endif
#if !defined(MBED_CONF_EVENTS_SHARED_STACKSIZE)
	#define MBED_CONF_EVENTS_SHARED_STACKSIZE (1024)
#endif
#if !defined(UNITY_INCLUDE_CONFIG_H)
	#define UNITY_INCLUDE_CONFIG_H
#endif


# endif
