
// Automatically generated configuration file.

# ifndef __MBED_CONFIG_DATA__
# define __MBED_CONFIG_DATA__

// Configuration parameters

#if !defined(MBED_CONF_PLATFORM_ERROR_DECODE_HTTP_URL_STR)
	#define MBED_CONF_PLATFORM_ERROR_DECODE_HTTP_URL_STR "\nFor more info, visit: https://armmbed.github.io/mbedos-error/?error=0x%08X"
#endif
#if !defined(MBED_CONF_DRIVERS_UART_SERIAL_TXBUF_SIZE)
	#define MBED_CONF_DRIVERS_UART_SERIAL_TXBUF_SIZE 256
#endif
#if !defined(MBED_CONF_PLATFORM_STDIO_BAUD_RATE)
	#define MBED_CONF_PLATFORM_STDIO_BAUD_RATE 9600
#endif
#if !defined(MBED_CONF_PLATFORM_MAX_ERROR_FILENAME_LEN)
	#define MBED_CONF_PLATFORM_MAX_ERROR_FILENAME_LEN 16
#endif
#if !defined(MBED_CONF_PLATFORM_ERROR_HIST_SIZE)
	#define MBED_CONF_PLATFORM_ERROR_HIST_SIZE 4
#endif
#if !defined(MBED_CONF_PLATFORM_ERROR_FILENAME_CAPTURE_ENABLED)
	#define MBED_CONF_PLATFORM_ERROR_FILENAME_CAPTURE_ENABLED 0
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_PLATFORM_DEFAULT_SERIAL_BAUD_RATE)
	#define MBED_CONF_PLATFORM_DEFAULT_SERIAL_BAUD_RATE 9600
#endif
#if !defined(MBED_CONF_PLATFORM_STDIO_BUFFERED_SERIAL)
	#define MBED_CONF_PLATFORM_STDIO_BUFFERED_SERIAL 0
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_PLATFORM_POLL_USE_LOWPOWER_TIMER)
	#define MBED_CONF_PLATFORM_POLL_USE_LOWPOWER_TIMER 0
#endif
#if !defined(MBED_CONF_PLATFORM_STDIO_FLUSH_AT_EXIT)
	#define MBED_CONF_PLATFORM_STDIO_FLUSH_AT_EXIT 1
#endif
#if !defined(MBED_CONF_PLATFORM_FORCE_NON_COPYABLE_ERROR)
	#define MBED_CONF_PLATFORM_FORCE_NON_COPYABLE_ERROR 0
#endif
#if !defined(MBED_CONF_PLATFORM_ERROR_ALL_THREADS_INFO)
	#define MBED_CONF_PLATFORM_ERROR_ALL_THREADS_INFO 0
#endif
#if !defined(MBED_CONF_PLATFORM_STDIO_CONVERT_NEWLINES)
	#define MBED_CONF_PLATFORM_STDIO_CONVERT_NEWLINES 0
#endif
#if !defined(MBED_CONF_DRIVERS_UART_SERIAL_RXBUF_SIZE)
	#define MBED_CONF_DRIVERS_UART_SERIAL_RXBUF_SIZE 256
#endif
#if !defined(MBED_CONF_PLATFORM_STDIO_CONVERT_TTY_NEWLINES)
	#define MBED_CONF_PLATFORM_STDIO_CONVERT_TTY_NEWLINES 0
#endif
#if !defined(MBED_MEM_TRACING_ENABLED)
	#define MBED_MEM_TRACING_ENABLED 0
#endif
#if !defined(MBED_CONF_PLATFORM_ERROR_HIST_ENABLED)
	#define MBED_CONF_PLATFORM_ERROR_HIST_ENABLED 0
#endif
#if !defined(MBED_CONF_ATMEL_RF_LOW_SPI_SPEED)
	#define MBED_CONF_ATMEL_RF_LOW_SPI_SPEED 3750000
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(MBED_CONF_ATMEL_RF_USE_SPI_SPACING_API)
	#define MBED_CONF_ATMEL_RF_USE_SPI_SPACING_API 0
#endif
#if !defined(MBED_CONF_ATMEL_RF_FULL_SPI_SPEED)
	#define MBED_CONF_ATMEL_RF_FULL_SPI_SPEED 7500000
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_ATMEL_RF_PROVIDE_DEFAULT)
	#define MBED_CONF_ATMEL_RF_PROVIDE_DEFAULT 0
#endif
#if !defined(MBED_CONF_ATMEL_RF_ASSUME_SPACED_SPI)
	#define MBED_CONF_ATMEL_RF_ASSUME_SPACED_SPI 1
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(MBED_CONF_ATMEL_RF_FULL_SPI_SPEED_BYTE_SPACING)
	#define MBED_CONF_ATMEL_RF_FULL_SPI_SPEED_BYTE_SPACING 250
#endif
#if !defined(MBED_CONF_MCR20A_PROVIDE_DEFAULT)
	#define MBED_CONF_MCR20A_PROVIDE_DEFAULT 0
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(MBED_CONF_DATAFLASH_BINARY_SIZE)
	#define MBED_CONF_DATAFLASH_BINARY_SIZE 0
#endif
#if !defined(MBED_CONF_DATAFLASH_DATAFLASH_SIZE)
	#define MBED_CONF_DATAFLASH_DATAFLASH_SIZE 0
#endif
#if !defined(MBED_CONF_DATAFLASH_SPI_MISO)
	#define MBED_CONF_DATAFLASH_SPI_MISO NC
#endif
#if !defined(MBED_CONF_DATAFLASH_SPI_CLK)
	#define MBED_CONF_DATAFLASH_SPI_CLK NC
#endif
#if !defined(MBED_CONF_DATAFLASH_SPI_MOSI)
	#define MBED_CONF_DATAFLASH_SPI_MOSI NC
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(MBED_CONF_DATAFLASH_SPI_CS)
	#define MBED_CONF_DATAFLASH_SPI_CS NC
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(MBED_CONF_SD_SPI_MOSI)
	#define MBED_CONF_SD_SPI_MOSI NC
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(MBED_CONF_SD_SPI_MISO)
	#define MBED_CONF_SD_SPI_MISO NC
#endif
#if !defined(MBED_CONF_SD_SPI_CS)
	#define MBED_CONF_SD_SPI_CS NC
#endif
#if !defined(MBED_CONF_SD_DEVICE_SPI)
	#define MBED_CONF_SD_DEVICE_SPI 1
#endif
#if !defined(MBED_CONF_SD_CMD0_IDLE_STATE_RETRIES)
	#define MBED_CONF_SD_CMD0_IDLE_STATE_RETRIES 5
#endif
#if !defined(MBED_CONF_SD_SD_INIT_FREQUENCY)
	#define MBED_CONF_SD_SD_INIT_FREQUENCY 100000
#endif
#if !defined(MBED_CONF_SD_CMD_TIMEOUT)
	#define MBED_CONF_SD_CMD_TIMEOUT 10000
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_SD_SPI_CLK)
	#define MBED_CONF_SD_SPI_CLK NC
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(MBED_CONF_SD_FSFAT_SDCARD_INSTALLED)
	#define MBED_CONF_SD_FSFAT_SDCARD_INSTALLED 1
#endif
#if !defined(MBED_CONF_SPIF_DRIVER_SPI_MOSI)
	#define MBED_CONF_SPIF_DRIVER_SPI_MOSI NC
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(MBED_CONF_SPIF_DRIVER_SPI_MISO)
	#define MBED_CONF_SPIF_DRIVER_SPI_MISO NC
#endif
#if !defined(MBED_CONF_SPIF_DRIVER_SPI_CS)
	#define MBED_CONF_SPIF_DRIVER_SPI_CS NC
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(MBED_CONF_SPIF_DRIVER_SPI_CLK)
	#define MBED_CONF_SPIF_DRIVER_SPI_CLK NC
#endif
#if !defined(MBED_CONF_SPIF_DRIVER_SPI_FREQ)
	#define MBED_CONF_SPIF_DRIVER_SPI_FREQ 40000000
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(MBED_CONF_ESP8266_DEBUG)
	#define MBED_CONF_ESP8266_DEBUG 0
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_ESP8266_PROVIDE_DEFAULT)
	#define MBED_CONF_ESP8266_PROVIDE_DEFAULT 0
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(MEM_FREE)
	#define MEM_FREE free
#endif
#if !defined(MEM_ALLOC)
	#define MEM_ALLOC malloc
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CFSTORE_STORAGE_DISABLE)
	#define CFSTORE_STORAGE_DISABLE 0
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(MBED_CONF_RTOS_TIMER_THREAD_STACK_SIZE)
	#define MBED_CONF_RTOS_TIMER_THREAD_STACK_SIZE 768
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(MBED_CONF_RTOS_IDLE_THREAD_STACK_SIZE)
	#define MBED_CONF_RTOS_IDLE_THREAD_STACK_SIZE 512
#endif
#if !defined(MBED_CONF_RTOS_MAIN_THREAD_STACK_SIZE)
	#define MBED_CONF_RTOS_MAIN_THREAD_STACK_SIZE 4096
#endif
#if !defined(MBED_CONF_RTOS_THREAD_STACK_SIZE)
	#define MBED_CONF_RTOS_THREAD_STACK_SIZE 4096
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(_RTE_)
	#define _RTE_
#endif
#if !defined(MBED_CONF_EVENTS_SHARED_EVENTSIZE)
	#define MBED_CONF_EVENTS_SHARED_EVENTSIZE 256
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(MBED_CONF_EVENTS_SHARED_DISPATCH_FROM_APPLICATION)
	#define MBED_CONF_EVENTS_SHARED_DISPATCH_FROM_APPLICATION 0
#endif
#if !defined(MBED_CONF_EVENTS_SHARED_STACKSIZE)
	#define MBED_CONF_EVENTS_SHARED_STACKSIZE 1024
#endif
#if !defined(MBED_CONF_EVENTS_SHARED_HIGHPRIO_STACKSIZE)
	#define MBED_CONF_EVENTS_SHARED_HIGHPRIO_STACKSIZE 1024
#endif
#if !defined(MBED_CONF_EVENTS_USE_LOWPOWER_TIMER_TICKER)
	#define MBED_CONF_EVENTS_USE_LOWPOWER_TIMER_TICKER 0
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(MBED_CONF_EVENTS_SHARED_HIGHPRIO_EVENTSIZE)
	#define MBED_CONF_EVENTS_SHARED_HIGHPRIO_EVENTSIZE 256
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(MBED_CONF_CELLULAR_RANDOM_MAX_START_DELAY)
	#define MBED_CONF_CELLULAR_RANDOM_MAX_START_DELAY 0
#endif
#if !defined(MBED_CONF_CELLULAR_USE_APN_LOOKUP)
	#define MBED_CONF_CELLULAR_USE_APN_LOOKUP 1
#endif
#if !defined(MBED_CONF_CELLULAR_DEBUG_AT)
	#define MBED_CONF_CELLULAR_DEBUG_AT 0
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(MBED_CONF_LORA_APPSKEY)
	#define MBED_CONF_LORA_APPSKEY {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
#endif
#if !defined(MBED_CONF_LORA_UPLINK_PREAMBLE_LENGTH)
	#define MBED_CONF_LORA_UPLINK_PREAMBLE_LENGTH 8
#endif
#if !defined(MBED_CONF_LORA_FSB_MASK_CHINA)
	#define MBED_CONF_LORA_FSB_MASK_CHINA {0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF}
#endif
#if !defined(MBED_CONF_LORA_AUTOMATIC_UPLINK_MESSAGE)
	#define MBED_CONF_LORA_AUTOMATIC_UPLINK_MESSAGE 1
#endif
#if !defined(MBED_CONF_LORA_TX_MAX_SIZE)
	#define MBED_CONF_LORA_TX_MAX_SIZE 64
#endif
#if !defined(MBED_CONF_LORA_APP_PORT)
	#define MBED_CONF_LORA_APP_PORT 15
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(MBED_CONF_LORA_DOWNLINK_PREAMBLE_LENGTH)
	#define MBED_CONF_LORA_DOWNLINK_PREAMBLE_LENGTH 5
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(MBED_CONF_LORA_NB_TRIALS)
	#define MBED_CONF_LORA_NB_TRIALS 12
#endif
#if !defined(MBED_CONF_LORA_MAX_SYS_RX_ERROR)
	#define MBED_CONF_LORA_MAX_SYS_RX_ERROR 10
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_LORA_DUTY_CYCLE_ON)
	#define MBED_CONF_LORA_DUTY_CYCLE_ON 1
#endif
#if !defined(MBED_CONF_LORA_DEVICE_ADDRESS)
	#define MBED_CONF_LORA_DEVICE_ADDRESS 0x00000000
#endif
#if !defined(MBED_CONF_LORA_OVER_THE_AIR_ACTIVATION)
	#define MBED_CONF_LORA_OVER_THE_AIR_ACTIVATION 1
#endif
#if !defined(MBED_CONF_LORA_DEVICE_EUI)
	#define MBED_CONF_LORA_DEVICE_EUI {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
#endif
#if !defined(MBED_CONF_LORA_APPLICATION_EUI)
	#define MBED_CONF_LORA_APPLICATION_EUI {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
#endif
#if !defined(MBED_CONF_LORA_PUBLIC_NETWORK)
	#define MBED_CONF_LORA_PUBLIC_NETWORK 1
#endif
#if !defined(MBED_CONF_LORA_PHY)
	#define MBED_CONF_LORA_PHY EU868
#endif
#if !defined(MBED_CONF_LORA_NWKSKEY)
	#define MBED_CONF_LORA_NWKSKEY {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
#endif
#if !defined(MBED_CONF_LORA_FSB_MASK)
	#define MBED_CONF_LORA_FSB_MASK {0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0x00FF}
#endif
#if !defined(MBED_CONF_LORA_LBT_ON)
	#define MBED_CONF_LORA_LBT_ON 0
#endif
#if !defined(MBED_CONF_LORA_APPLICATION_KEY)
	#define MBED_CONF_LORA_APPLICATION_KEY {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
#endif
#if !defined(MBED_CONF_LORA_DUTY_CYCLE_ON_JOIN)
	#define MBED_CONF_LORA_DUTY_CYCLE_ON_JOIN 1
#endif
#if !defined(MBED_CONF_LORA_ADR_ON)
	#define MBED_CONF_LORA_ADR_ON 1
#endif
#if !defined(MBED_CONF_LWIP_IPV6_ENABLED)
	#define MBED_CONF_LWIP_IPV6_ENABLED 0
#endif
#if !defined(MBED_CONF_LWIP_TCP_SOCKET_MAX)
	#define MBED_CONF_LWIP_TCP_SOCKET_MAX 4
#endif
#if !defined(MBED_CONF_LWIP_ENABLE_PPP_TRACE)
	#define MBED_CONF_LWIP_ENABLE_PPP_TRACE 0
#endif
#if !defined(NSAPI_PPP_AVAILABLE)
	#define NSAPI_PPP_AVAILABLE 0
#endif
#if !defined(NSAPI_PPP_IPV4_AVAILABLE)
	#define NSAPI_PPP_IPV4_AVAILABLE 1
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(MBED_CONF_LWIP_USE_MBED_TRACE)
	#define MBED_CONF_LWIP_USE_MBED_TRACE 0
#endif
#if !defined(MBED_CONF_LWIP_TCP_ENABLED)
	#define MBED_CONF_LWIP_TCP_ENABLED 1
#endif
#if !defined(MBED_CONF_LWIP_TCP_SERVER_MAX)
	#define MBED_CONF_LWIP_TCP_SERVER_MAX 4
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(MBED_CONF_LWIP_PPP_THREAD_STACKSIZE)
	#define MBED_CONF_LWIP_PPP_THREAD_STACKSIZE 768
#endif
#if !defined(MBED_CONF_LWIP_ADDR_TIMEOUT)
	#define MBED_CONF_LWIP_ADDR_TIMEOUT 5
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_LWIP_ADDR_TIMEOUT_MODE)
	#define MBED_CONF_LWIP_ADDR_TIMEOUT_MODE 1
#endif
#if !defined(MBED_CONF_LWIP_ETHERNET_ENABLED)
	#define MBED_CONF_LWIP_ETHERNET_ENABLED 1
#endif
#if !defined(NSAPI_PPP_IPV6_AVAILABLE)
	#define NSAPI_PPP_IPV6_AVAILABLE 0
#endif
#if !defined(MBED_CONF_LWIP_DEFAULT_THREAD_STACKSIZE)
	#define MBED_CONF_LWIP_DEFAULT_THREAD_STACKSIZE 512
#endif
#if !defined(MBED_CONF_LWIP_IPV4_ENABLED)
	#define MBED_CONF_LWIP_IPV4_ENABLED 1
#endif
#if !defined(MBED_CONF_LWIP_DEBUG_ENABLED)
	#define MBED_CONF_LWIP_DEBUG_ENABLED 0
#endif
#if !defined(MBED_CONF_LWIP_TCPIP_THREAD_STACKSIZE)
	#define MBED_CONF_LWIP_TCPIP_THREAD_STACKSIZE 1200
#endif
#if !defined(MBED_CONF_LWIP_IP_VER_PREF)
	#define MBED_CONF_LWIP_IP_VER_PREF 4
#endif
#if !defined(MBED_CONF_LWIP_MEM_SIZE)
	#define MBED_CONF_LWIP_MEM_SIZE 25600
#endif
#if !defined(MBED_CONF_LWIP_UDP_SOCKET_MAX)
	#define MBED_CONF_LWIP_UDP_SOCKET_MAX 4
#endif
#if !defined(MBED_CONF_LWIP_SOCKET_MAX)
	#define MBED_CONF_LWIP_SOCKET_MAX 4
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(MBED_CONF_MBED_MESH_API_THREAD_MASTER_KEY)
	#define MBED_CONF_MBED_MESH_API_THREAD_MASTER_KEY {0x10, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff}
#endif
#if !defined(MBED_CONF_MBED_MESH_API_THREAD_CONFIG_ML_PREFIX)
	#define MBED_CONF_MBED_MESH_API_THREAD_CONFIG_ML_PREFIX {0xfd, 0x0, 0x0d, 0xb8, 0x0, 0x0, 0x0, 0x0}
#endif
#if !defined(MBED_CONF_MBED_MESH_API_THREAD_USE_STATIC_LINK_CONFIG)
	#define MBED_CONF_MBED_MESH_API_THREAD_USE_STATIC_LINK_CONFIG 1
#endif
#if !defined(MBED_CONF_MBED_MESH_API_6LOWPAN_ND_DEVICE_TYPE)
	#define MBED_CONF_MBED_MESH_API_6LOWPAN_ND_DEVICE_TYPE NET_6LOWPAN_ROUTER
#endif
#if !defined(MBED_CONF_MBED_MESH_API_THREAD_PSKD)
	#define MBED_CONF_MBED_MESH_API_THREAD_PSKD "ABCDEFGH"
#endif
#if !defined(MBED_CONF_MBED_MESH_API_THREAD_DEVICE_TYPE)
	#define MBED_CONF_MBED_MESH_API_THREAD_DEVICE_TYPE MESH_DEVICE_TYPE_THREAD_ROUTER
#endif
#if !defined(MBED_CONF_MBED_MESH_API_6LOWPAN_ND_CHANNEL_MASK)
	#define MBED_CONF_MBED_MESH_API_6LOWPAN_ND_CHANNEL_MASK 0x7fff800
#endif
#if !defined(MBED_CONF_MBED_MESH_API_THREAD_CONFIG_PSKC)
	#define MBED_CONF_MBED_MESH_API_THREAD_CONFIG_PSKC {0xc8, 0xa6, 0x2e, 0xae, 0xf3, 0x68, 0xf3, 0x46, 0xa9, 0x9e, 0x57, 0x85, 0x98, 0x9d, 0x1c, 0xd0}
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(MBED_CONF_MBED_MESH_API_6LOWPAN_ND_CHANNEL)
	#define MBED_CONF_MBED_MESH_API_6LOWPAN_ND_CHANNEL 0
#endif
#if !defined(MBED_CONF_MBED_MESH_API_6LOWPAN_ND_PANID_FILTER)
	#define MBED_CONF_MBED_MESH_API_6LOWPAN_ND_PANID_FILTER 0xffff
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(MBED_CONF_MBED_MESH_API_HEAP_SIZE)
	#define MBED_CONF_MBED_MESH_API_HEAP_SIZE 32500
#endif
#if !defined(MBED_CONF_MBED_MESH_API_6LOWPAN_ND_SEC_LEVEL)
	#define MBED_CONF_MBED_MESH_API_6LOWPAN_ND_SEC_LEVEL 5
#endif
#if !defined(MBED_CONF_MBED_MESH_API_6LOWPAN_ND_PSK_KEY_ID)
	#define MBED_CONF_MBED_MESH_API_6LOWPAN_ND_PSK_KEY_ID 1
#endif
#if !defined(MBED_CONF_MBED_MESH_API_THREAD_CONFIG_NETWORK_NAME)
	#define MBED_CONF_MBED_MESH_API_THREAD_CONFIG_NETWORK_NAME "Thread Network"
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_MBED_MESH_API_6LOWPAN_ND_CHANNEL_PAGE)
	#define MBED_CONF_MBED_MESH_API_6LOWPAN_ND_CHANNEL_PAGE 0
#endif
#if !defined(MBED_CONF_MBED_MESH_API_THREAD_CONFIG_CHANNEL)
	#define MBED_CONF_MBED_MESH_API_THREAD_CONFIG_CHANNEL 22
#endif
#if !defined(MBED_CONF_MBED_MESH_API_6LOWPAN_ND_PSK_KEY)
	#define MBED_CONF_MBED_MESH_API_6LOWPAN_ND_PSK_KEY {0xa0, 0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7, 0xa8, 0xa9, 0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf}
#endif
#if !defined(MBED_CONF_MBED_MESH_API_THREAD_CONFIG_COMMISSIONING_DATASET_TIMESTAMP)
	#define MBED_CONF_MBED_MESH_API_THREAD_CONFIG_COMMISSIONING_DATASET_TIMESTAMP 0x10000
#endif
#if !defined(MBED_CONF_MBED_MESH_API_THREAD_SECURITY_POLICY)
	#define MBED_CONF_MBED_MESH_API_THREAD_SECURITY_POLICY 255
#endif
#if !defined(MBED_CONF_MBED_MESH_API_THREAD_CONFIG_CHANNEL_MASK)
	#define MBED_CONF_MBED_MESH_API_THREAD_CONFIG_CHANNEL_MASK 0x7fff800
#endif
#if !defined(MBED_CONF_MBED_MESH_API_6LOWPAN_ND_SECURITY_MODE)
	#define MBED_CONF_MBED_MESH_API_6LOWPAN_ND_SECURITY_MODE NONE
#endif
#if !defined(MBED_CONF_MBED_MESH_API_USE_MALLOC_FOR_HEAP)
	#define MBED_CONF_MBED_MESH_API_USE_MALLOC_FOR_HEAP 0
#endif
#if !defined(MBED_CONF_MBED_MESH_API_THREAD_CONFIG_EXTENDED_PANID)
	#define MBED_CONF_MBED_MESH_API_THREAD_CONFIG_EXTENDED_PANID {0xf1, 0xb5, 0xa1, 0xb2,0xc4, 0xd5, 0xa1, 0xbd }
#endif
#if !defined(MBED_CONF_MBED_MESH_API_THREAD_CONFIG_CHANNEL_PAGE)
	#define MBED_CONF_MBED_MESH_API_THREAD_CONFIG_CHANNEL_PAGE 0
#endif
#if !defined(MBED_CONF_MBED_MESH_API_THREAD_CONFIG_PANID)
	#define MBED_CONF_MBED_MESH_API_THREAD_CONFIG_PANID 0x0700
#endif
#if !defined(MBED_CONF_MBED_MESH_API_HEAP_STAT_INFO)
	#define MBED_CONF_MBED_MESH_API_HEAP_STAT_INFO NULL
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(MBED_CONF_NANOSTACK_HAL_EVENT_LOOP_USE_MBED_EVENTS)
	#define MBED_CONF_NANOSTACK_HAL_EVENT_LOOP_USE_MBED_EVENTS 0
#endif
#if !defined(MBED_CONF_NANOSTACK_HAL_CRITICAL_SECTION_USABLE_FROM_INTERRUPT)
	#define MBED_CONF_NANOSTACK_HAL_CRITICAL_SECTION_USABLE_FROM_INTERRUPT 0
#endif
#if !defined(MBED_CONF_NANOSTACK_HAL_EVENT_LOOP_THREAD_STACK_SIZE)
	#define MBED_CONF_NANOSTACK_HAL_EVENT_LOOP_THREAD_STACK_SIZE 6144
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_NANOSTACK_HAL_EVENT_LOOP_DISPATCH_FROM_APPLICATION)
	#define MBED_CONF_NANOSTACK_HAL_EVENT_LOOP_DISPATCH_FROM_APPLICATION 0
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(MBED_CONF_NANOSTACK_HAL_NVM_CFSTORE)
	#define MBED_CONF_NANOSTACK_HAL_NVM_CFSTORE 0
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(MBED_CONF_NANOSTACK_CONFIGURATION)
	#define MBED_CONF_NANOSTACK_CONFIGURATION nanostack_full
#endif
#if !defined(NS_USE_EXTERNAL_MBED_TLS)
	#define NS_USE_EXTERNAL_MBED_TLS
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(MBED_CONF_PPP_CELL_IFACE_APN_LOOKUP)
	#define MBED_CONF_PPP_CELL_IFACE_APN_LOOKUP 1
#endif
#if !defined(MBED_CONF_NSAPI_DNS_RESPONSE_WAIT_TIME)
	#define MBED_CONF_NSAPI_DNS_RESPONSE_WAIT_TIME 5000
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(MBED_CONF_PPP_CELL_IFACE_AT_PARSER_BUFFER_SIZE)
	#define MBED_CONF_PPP_CELL_IFACE_AT_PARSER_BUFFER_SIZE 256
#endif
#if !defined(MBED_CONF_NSAPI_DNS_CACHE_SIZE)
	#define MBED_CONF_NSAPI_DNS_CACHE_SIZE 3
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_NSAPI_DEFAULT_WIFI_SECURITY)
	#define MBED_CONF_NSAPI_DEFAULT_WIFI_SECURITY NONE
#endif
#if !defined(MBED_CONF_NSAPI_DEFAULT_MESH_TYPE)
	#define MBED_CONF_NSAPI_DEFAULT_MESH_TYPE THREAD
#endif
#if !defined(MBED_CONF_NSAPI_DNS_RETRIES)
	#define MBED_CONF_NSAPI_DNS_RETRIES 0
#endif
#if !defined(MBED_CONF_NSAPI_DEFAULT_STACK)
	#define MBED_CONF_NSAPI_DEFAULT_STACK LWIP
#endif
#if !defined(MBED_CONF_PPP_CELL_IFACE_BAUD_RATE)
	#define MBED_CONF_PPP_CELL_IFACE_BAUD_RATE 115200
#endif
#if !defined(MBED_CONF_NSAPI_DNS_TOTAL_ATTEMPTS)
	#define MBED_CONF_NSAPI_DNS_TOTAL_ATTEMPTS 3
#endif
#if !defined(MBED_CONF_PPP_CELL_IFACE_AT_PARSER_TIMEOUT)
	#define MBED_CONF_PPP_CELL_IFACE_AT_PARSER_TIMEOUT 8000
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(MBED_LFS_LOOKAHEAD)
	#define MBED_LFS_LOOKAHEAD 512
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(MBED_LFS_INTRINSICS)
	#define MBED_LFS_INTRINSICS 1
#endif
#if !defined(MBED_LFS_READ_SIZE)
	#define MBED_LFS_READ_SIZE 64
#endif
#if !defined(MBED_LFS_ENABLE_INFO)
	#define MBED_LFS_ENABLE_INFO 0
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(MBED_LFS_PROG_SIZE)
	#define MBED_LFS_PROG_SIZE 64
#endif
#if !defined(MBED_LFS_BLOCK_SIZE)
	#define MBED_LFS_BLOCK_SIZE 512
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(NVSTORE_MAX_KEYS)
	#define NVSTORE_MAX_KEYS 16
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(NVSTORE_ENABLED)
	#define NVSTORE_ENABLED 1
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif
#if !defined(LPTICKER_DELAY_TICKS)
	#define LPTICKER_DELAY_TICKS 1
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE USE_PLL_HSI
#endif
#if !defined(MBED_CONF_TARGET_LSE_AVAILABLE)
	#define MBED_CONF_TARGET_LSE_AVAILABLE 0
#endif
#if !defined(MBED_CONF_TARGET_LPUART_CLOCK_SOURCE)
	#define MBED_CONF_TARGET_LPUART_CLOCK_SOURCE USE_LPUART_CLK_LSE|USE_LPUART_CLK_PCLK1
#endif


# endif
